name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
jobs:
  build: 
    run-ons: ubuntu-tatest

    steps:
    - uses: actions/checkout@v3

    - run: echo "Die Environment ist ${{ inputs.environment }}"
    - run: echo "Der Wert der Environment-Variable DISCRITPION ist ${{ vars.DESCRIPTION }}"
    - run: echo "Mein Benutzer-Secret ist ${{ secrets.MONGODB_USERNAME }}"
    
